# Generated by Django 6.0.5 on 2026-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_security_locked',
            field=models.BooleanField(default=True),
        ),
    ]
