# Generated by Codex on 2026-05-30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grid_x', models.PositiveSmallIntegerField(default=0)),
                ('grid_y', models.PositiveSmallIntegerField(default=0)),
                ('grid_w', models.PositiveSmallIntegerField(default=4)),
                ('grid_h', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grid_y', 'grid_x', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['owner', 'grid_y', 'grid_x'], name='layout_room_owner_i_501dd3_idx'),
        ),
    ]
