# Generated by Codex on 2026-05-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_appliance'),
        ('devices', '0002_device_room'),
    ]

    operations = []
