# Generated by Django 6.0.5 on 2026-05-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('telemetry', '0002_telemetryreading_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device'),
        ),
    ]
