# Generated by Django 6.0.5 on 2026-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_telemetryreading_pir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetryreading',
            name='device',
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='device_id',
            field=models.CharField(blank=True, db_column='device_id', max_length=50, null=True),
        ),
    ]
