# Generated by hand on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_float_power_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='c1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='c2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='c3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='c4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='appliance_id',
            field=models.IntegerField(blank=True, null=True, db_column='appliance_id'),
        ),
    ]
